### PR TITLE
Create Taipei-Day-Trip-Website Homepage

### PR DESCRIPTION
**Pull request by shaoyunjian**
Good day! @cwpeng 
This is Shaoyun(劭芸). Here is my link below. 
http://3.211.21.229:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your layout in 360px width devices will break: exceeding screen width, keyword input width is too small.
3 211 21 229_3000_(Samsung Galaxy S8+)

**Comment by shaoyunjian** [comment]
Fixed it! Could you please check it again?
http://3.211.21.229:3000/

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by shaoyunjian** [comment]
Thanks !! 😄

**Pull request merged**
